instance:
  opts:
    allocated_storage: 20
    auto_minor_version_upgrade: false
    backup_retention_period: 7
    db_instance_class: db.t4g.micro
    db_instance_identifier: db-instance-2
    db_name: database2
    db_parameter_group: pg-1
    db_subnet_group_name: default-vpc-0a9656a8691710528
    deletion_protection: false
    enable_cloudwatch_logs_exports:
    - postgresql
    - upgrade
    engine: postgres
    engine_version: "17.2"
    license_model: postgresql-license
    skip_final_snapshot: true
    publicly_accessible: true
  creds:
    master_user_name: postgres
    master_user_password: WioSna$9631uj